name: run main.py

on:
  schedule:
    - cron: '0 0 * * *'   # 01:00 local (UTC+1)
    - cron: '0 6 * * *'   # 07:00 local (UTC+1)
    - cron: '0 12 * * *'  # 13:00 local (UTC+1)
    - cron: '0 18 * * *'  # 19:00 local (UTC+1)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py
      env: 
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.API_ACCESS_KEY }}
        SITEMAP_URL: 'https://www.recruityard.com/sitemap.xml'